version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - DATADOG_KEY=${DATADOG_KEY}
      - GRAFANA_TOKEN=${GRAFANA_TOKEN}
    depends_on:
      - redis

  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend/build:/usr/share/nginx/html
    depends_on:
      - backend

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
